# Generated by Django 4.1.5 on 2023-02-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Category',
            field=models.CharField(choices=[('eye', 'eyes specialist'), ('lung', 'lungs specialist'), ('heart', 'heart specialist'), ('legs', 'legs specialist')], max_length=100),
        ),
    ]
